
import { BrokerInfo, BrokerType } from "../types";

const BROKER_DB: Record<string, { type: BrokerType; desc: string }> = {
  // --- RICH / KUAT (Institusi & Asing) ---
  CS: { type: 'RICH', desc: 'Credit Suisse: Asing top, hold aman.' },
  MS: { type: 'RICH', desc: 'Morgan Stanley: Asing US.' },
  UB: { type: 'RICH', desc: 'UBS: Asing kuat.' },
  BK: { type: 'RICH', desc: 'JP Morgan: Arus institusi.' },
  AK: { type: 'RICH', desc: 'UBS Patungan.' },
  YP: { type: 'RICH', desc: 'Mirae Asset: Top Ritel Pro & Institusi.' },
  ZP: { type: 'RICH', desc: 'MNC Sekuritas: Institusi Lokal.' },
  HD: { type: 'RICH', desc: 'KGI Sekuritas.' },
  RX: { type: 'RICH', desc: 'RHB Sekuritas.' },
  DU: { type: 'RICH', desc: 'Deutsche Sekuritas.' },
  CG: { type: 'RICH', desc: 'CGS-CIMB.' },
  KZ: { type: 'RICH', desc: 'CLSA Sekuritas.' },
  DR: { type: 'RICH', desc: 'Danareksa (Institusi).' },
  LH: { type: 'RICH', desc: 'Lautandhana.' },
  AH: { type: 'RICH', desc: 'Andalan.' },
  GW: { type: 'RICH', desc: 'Golden.' },
  RB: { type: 'RICH', desc: 'RHB.' },
  TP: { type: 'RICH', desc: 'Trimegah (Institusi).' },
  KK: { type: 'RICH', desc: 'Kresna.' },
  LS: { type: 'RICH', desc: 'Laurent.' },

  // --- KONGLO SPESIAL (Market Maker / Group) ---
  HP: { type: 'KONGLO', desc: 'Henan Putihrai: Spesialis grup konglomerasi.' },
  DX: { type: 'KONGLO', desc: 'Bahana (Kadang Institusi/Konglo).' },
  LG: { type: 'KONGLO', desc: 'Trimegah (Akun Khusus).' },
  MU: { type: 'KONGLO', desc: 'Minna Padi.' },
  ES: { type: 'KONGLO', desc: 'Ekosistem Grup Tertentu.' },
  MG: { type: 'KONGLO', desc: 'Semesta Indovest (Sering jadi MM).' },

  // --- AMPAS / RITEL (Crowd / Lemah) ---
  XL: { type: 'AMPAS', desc: 'Stockbit: Ritel crowd, panic easy.' },
  XC: { type: 'AMPAS', desc: 'Ajaib: Ritel pemula & mahasiswa.' },
  PD: { type: 'AMPAS', desc: 'Indo Premier: Ritel massal.' },
  CC: { type: 'AMPAS', desc: 'Mandiri Sekuritas (Akun Ritel).' },
  CP: { type: 'AMPAS', desc: 'Valbury (Ritel).' },
  NI: { type: 'AMPAS', desc: 'BNI Sekuritas (Ritel).' },
  IF: { type: 'AMPAS', desc: 'Samuel Sekuritas (Ritel).' },
  BB: { type: 'AMPAS', desc: 'Verdhana (Ritel).' },
  SS: { type: 'AMPAS', desc: 'Ajaib (Kode lama/baru).' },
  BQ: { type: 'AMPAS', desc: 'Korea Investment (Ritel).' },
  GR: { type: 'AMPAS', desc: 'Panin (Ritel).' },
  SA: { type: 'AMPAS', desc: 'Ritel Kecil.' },
  SC: { type: 'AMPAS', desc: 'Ritel Kecil.' },
  SF: { type: 'AMPAS', desc: 'Surya Fajar.' },
  SH: { type: 'AMPAS', desc: 'Artha Sekuritas (Ritel).' },
  SQ: { type: 'AMPAS', desc: 'BCA Sekuritas (Ritel).' },
  TF: { type: 'AMPAS', desc: 'Universal.' },
  TS: { type: 'AMPAS', desc: 'Tri Megah (Ritel).' },
  TX: { type: 'AMPAS', desc: 'Ritel.' },
  XA: { type: 'AMPAS', desc: 'Ritel.' },
  YB: { type: 'AMPAS', desc: 'Mega Capital (Ritel).' },
  YJ: { type: 'AMPAS', desc: 'Lotus (Ritel).' },
  YO: { type: 'AMPAS', desc: 'Amantara.' },
  ZR: { type: 'AMPAS', desc: 'Bumiputera.' },

  // --- CAMPUR (Mixed / Unknown / Tidak Signifikan) ---
  AD: { type: 'CAMPUR', desc: 'Oso Sekuritas.' },
  AF: { type: 'CAMPUR', desc: 'Harita.' },
  AG: { type: 'CAMPUR', desc: 'Kiwoom.' },
  AI: { type: 'CAMPUR', desc: 'UOB Kay Hian.' },
  AJ: { type: 'CAMPUR', desc: 'Pillars.' },
  AN: { type: 'CAMPUR', desc: 'Wanteg.' },
  AO: { type: 'CAMPUR', desc: 'Erdikha.' },
  AP: { type: 'CAMPUR', desc: 'Pacific.' },
  AR: { type: 'CAMPUR', desc: 'Binaartha.' },
  AZ: { type: 'CAMPUR', desc: 'Sucor (Campur Ritel/Institusi).' },
  BF: { type: 'CAMPUR', desc: 'Inti Fikasa.' },
  BS: { type: 'CAMPUR', desc: 'Equity.' },
  BZ: { type: 'CAMPUR', desc: 'Batavia.' },
  DD: { type: 'CAMPUR', desc: 'Makinta.' },
  DM: { type: 'CAMPUR', desc: 'Masindo.' },
  DP: { type: 'CAMPUR', desc: 'DBS Vickers.' },
  EL: { type: 'CAMPUR', desc: 'Evergreen.' },
  FO: { type: 'CAMPUR', desc: 'Forte.' },
  FS: { type: 'CAMPUR', desc: 'Fasilitas.' },
  FZ: { type: 'CAMPUR', desc: 'Waterfront.' },
  IC: { type: 'CAMPUR', desc: 'BCA (Campur).' },
  ID: { type: 'CAMPUR', desc: 'Anugerah.' },
  IH: { type: 'CAMPUR', desc: 'Pacific 2000.' },
  II: { type: 'CAMPUR', desc: 'Danatama.' },
  IN: { type: 'CAMPUR', desc: 'Investindo.' },
  IT: { type: 'CAMPUR', desc: 'Inti Teladan.' },
  IU: { type: 'CAMPUR', desc: 'Indo Capital.' },
  JB: { type: 'CAMPUR', desc: 'Jasa Utama.' },
  KI: { type: 'CAMPUR', desc: 'Ciptadana.' },
  KS: { type: 'CAMPUR', desc: 'Karta.' },
  MI: { type: 'CAMPUR', desc: 'Victoria.' },
  MK: { type: 'CAMPUR', desc: 'MNC (Campur).' },
  OD: { type: 'CAMPUR', desc: 'Danareksa.' },
  OK: { type: 'CAMPUR', desc: 'Nett.' },
  PC: { type: 'CAMPUR', desc: 'Panca Global.' },
  PF: { type: 'CAMPUR', desc: 'Danasakti.' },
  PG: { type: 'CAMPUR', desc: 'Panca Global.' },
  PI: { type: 'CAMPUR', desc: 'Pendanaan.' },
  PO: { type: 'CAMPUR', desc: 'Pilar.' },
  PP: { type: 'CAMPUR', desc: 'Aldiracita.' },
  PS: { type: 'CAMPUR', desc: 'Paramitra.' },
  RG: { type: 'CAMPUR', desc: 'Profindo.' },
  RO: { type: 'CAMPUR', desc: 'NISP.' },
  RS: { type: 'CAMPUR', desc: 'Yulie.' },
  YU: { type: 'CAMPUR', desc: 'CIMB.' },
  KAF: { type: 'CAMPUR', desc: 'KAF Sekuritas.' }
};

export const getBrokerInfo = (code: string): BrokerInfo => {
  const c = code.toUpperCase().trim();
  if (BROKER_DB[c]) return { code: c, ...BROKER_DB[c] };
  return { code: c, type: 'CAMPUR', desc: 'Broker kategori campur atau tidak terdaftar.' };
};
